### ISSUE TITLE
OpenShift V3 version is very out of date.

### ISSUE THREAD

**Issue by maxamillion** [DBuildService/ansible-osbs#10]
Upstream OpenShift V3 has released version 1.0 which incorporates many changes including renaming of their command line tools as well as certain administrative commands no longer being in the `ex` "experimental" command namespace so currently the OpenShift environment deployed with this ansible playbook does not correspond with upstream documentation.

**Comment by mmilata** [comment]
Check out the _openshift-1.0.0_ branch. The old version is in _master_ because that's what we have currently deployed. Perhaps it should be the other way around ...

**Comment by maxamillion** [comment]
Thanks!
