### ISSUE TITLE
Turning OpenShift authentication off fails

### ISSUE THREAD

**Issue by bkabrda** [DBuildService/ansible-osbs#3]
Hi, I'm trying to use ansible-osbs on a virtual machine with clean install of CentOS 7.1. I'm ending up with this failure:

```
TASK: [osbs_builder | openshift auth - clear] ********************************* 
failed: [192.168.122.211] => {"changed": true, "cmd": ["openshift", "ex", "policy", "-n", "master", "remove-role-from-group", "cluster-admin", "system:authenticated", "system:unauthenticated"], "delta": "0:00:00.859051", "end": "2015-05-15 04:03:11.889733", "rc": 255, "start": "2015-05-15 04:03:11.030682", "warnings": []}
stderr: F0515 04:03:11.887865    6663 remove_group.go:43] Put https://192.168.122.211:8443/osapi/v1beta1/roleBindings/cluster-admins?namespace=master: EOF
```

Trying to invoke the command manually on the system, I get:

```
[root@localhost ~]# export OPENSHIFTCONFIG=/var/lib/openshift/openshift.local.certificates/admin/.kubeconfig 
[root@localhost ~]# openshift ex policy -n master remove-role-from-group cluster-admin system:authenticated system:unauthenticated
F0515 04:09:50.853455    7746 remove_group.go:43] Get https://192.168.122.211:8443/osapi/v1beta1/policyBindings/master?namespace=master: dial tcp 192.168.122.211:8443: connection refused
```

**Comment by bkabrda** [comment]
Hmm, strange. It seems that the command fails randomly with different error messages and sometimes it even succeeds. Furthermore, running `curl https://192.168.122.211:8443/` succeds about 20 % of the time and rest of the time it fails with `curl: (7) Failed connect to 192.168.122.211:8443; Connection refused`. Perhaps a bug in OpenShift? I'm running `openshift-0.4.4-1.osbs.el7.centos.x86_64`, has anyone experienced failures like this one?

**Comment by twaugh** [comment]
Yes, I've seen that too.

**Comment by mmilata** [comment]
Yeah, I encountered that yesterday. Usually just running the playbook again succeeded. Almost looks like sleeping some magical number of seconds after starting the service is needed:(

Regarding the 20% success rate of connecting to the daemon, I haven't seen that. Is there anything suspicious in the journal?

**Comment by bkabrda** [comment]
Well the problem is that sleeping a magical number of seconds doesn't help, because the command fails and succeeds completely randomly :(

Interesting, journal contains these lines:

```
May 15 04:33:03 localhost.localdomain openshift[12228]: masterKubeConfig: invalid value '/var/lib/openshift/openshift.local.certificates/node-localhost.localdomain/.kubeconfig': could not read file
May 15 04:33:03 localhost.localdomain openshift[12228]: servingInfo.keyFile: invalid value '/var/lib/openshift/openshift.local.certificates/node-localhost.localdomain/server.key': could not read file
May 15 04:33:03 localhost.localdomain openshift[12228]: servingInfo.certFile: invalid value '/var/lib/openshift/openshift.local.certificates/node-localhost.localdomain/server.crt': could not read file
```

I'm going to try to find out what's wrong with these.

**Comment by bkabrda** [comment]
Hmm, so the problem is that the referenced files don't exist - to be more precise, they're elsewhere:

```
[root@localhost ~]# ls /var/lib/openshift/openshift.local.certificates/node-localhost.localdomain/.kubeconfig
ls: cannot access /var/lib/openshift/openshift.local.certificates/node-localhost.localdomain/.kubeconfig: No such file or directory
[root@localhost ~]# ls /var/lib/openshift/openshift.local.certificates/node-localhost/.kubeconfig 
/var/lib/openshift/openshift.local.certificates/node-localhost/.kubeconfig
```

(The `.localdomain` part is missing from the directory name)

**Comment by mmilata** [comment]
Looks like the playbook is generating wrong path in the configuration file. Let me investigate.

**Comment by mmilata** [comment]
@bkabrda Can you please send me the output of `ansible -i hosts all -m setup -v`. In the meantime you can probably work around the problem by adding `<outside_ip_address> localhost.localdomain` to `/etc/hosts`, removing `localhost.localdomain` from other lines and re-running the playbook.

**Comment by bkabrda** [comment]
Output of `ansible -i hosts all -m setup -v`: [1]

I tried your suggestion with `/etc/hosts` rebooted the virtual machine and reran the playbook, but it doesn't work; the errors in journal are still the same.

[1] http://fpaste.org/222211/81767143/

**Comment by bkabrda** [comment]
So it seems that the `/etc/hosts` solution worked, but I also had to `rm -rf /var/lib/openshift/*` and rerun the playbook again.

**Comment by mmilata** [comment]
I believe openshift needs the machine hostname to be set to something that resolves to the machine's IP address (and I guess the IP address must resolve back to the hostname). I pushed 8e4683e for cases where you want to set the hostname to the fqdn ansible knows the machine under.

Anyway, I've seen the message even with correct dns setup. I'll try to create some minimal reproducer for this issue and submit it as an openshift bug.

**Comment by mmilata** [comment]
Eh, that didn't do what I thought. Now you can set the hostname explicitly, at least.

**Comment by TomasTomecek** [comment]
You are right Martin. As far as I remember, hostname has to match dns entry. Would be great to get some info regarding that from openshift team and put it to deployment docs.
